bedroom_radio_on:
  alias: "Schlafzimmer Radio: An"
  mode: restart
  sequence:
  - service: media_player.play_media
    data:
      entity_id: media_player.mpd
      media_content_type: playlist
      media_content_id: live
    entity_id: media_player.mpd
  - service: media_player.volume_set
    data:
      entity_id: media_player.mpd
      volume_level: 1

  
bedroom_radio_off:
  alias: "Schlafzimmer Radio: Aus"
  mode: restart
  sequence:
  - service: media_player.media_stop
    data: {}
    entity_id: media_player.mpd


bedroom_lights_off:
  alias: "Schlafzimmer Licht: Aus"
  sequence:
  - service: light.turn_off
    entity_id: light.bedroom_led_1
  - service: light.turn_off
    entity_id: light.bedroom_led_2


bedroom_lights_half:
  alias: "Schlafzimmer Licht: Halb"
  sequence:
  - service: light.turn_on
    entity_id: light.bedroom_led_1
    data:
      brightness_pct: 50
      color_temp: 370
  - service: light.turn_on
    entity_id: light.bedroom_led_2
    data:
      brightness_pct: 50
      color_temp: 370


bedroom_lights_full:
  alias: "Schlafzimmer Licht: Voll"
  sequence:
  - service: light.turn_on
    entity_id: light.bedroom_led_1
    data:
      brightness: 255
      color_temp: 370
  - service: light.turn_on
    entity_id: light.bedroom_led_2
    data:
      brightness: 255
      color_temp: 370
