


- alias: Bedroom Button 1
  trigger:
  - device_id: cb927dc8f9bc81d7fad027c512a60c80
    domain: zha
    platform: device
    type: remote_button_alt_short_press
    subtype: button_1
  action:
    - service: light.turn_on
      entity_id: light.bedroom_led_1
      data:
        brightness_pct: 25
    - service: light.turn_on
      entity_id: light.bedroom_led_2
      data:
        brightness_pct: 25



- alias: Bedroom Button 2
  trigger:
  - device_id: cb927dc8f9bc81d7fad027c512a60c80
    domain: zha
    platform: device
    type: remote_button_alt_short_press
    subtype: button_2
  action:
    - service: light.turn_off
      entity_id: light.bedroom_led_1
    - service: light.turn_off
      entity_id: light.bedroom_led_2




- alias: Wake-up Alarm
  trigger:
  - platform: time
    at: input_datetime.wakeup_time
  condition:
  - condition: state
    entity_id: input_boolean.wakeup_alarm
    state: 'on'
  action:
  - service: script.bedroom_radio_on
  - service: timer.start
    entity_id: timer.wakeup_alarm_timeout
    data:
      duration: '00:15:00'



- alias: Alarm auto-off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.wakeup_alarm_timeout
  condition: []
  action:
  - service: script.bedroom_radio_off


