#
# Buttons
#

- alias: Bedroom Button 1
  trigger:
  - device_id: cb927dc8f9bc81d7fad027c512a60c80
    domain: zha
    platform: device
    type: remote_button_alt_short_press
    subtype: button_1
  action:
  - service: input_select.select_option
    entity_id: input_select.bedroom_mode
    data:
      option: 'Wakedown'    

- alias: Bedroom Button 2
  trigger:
  - device_id: cb927dc8f9bc81d7fad027c512a60c80
    domain: zha
    platform: device
    type: remote_button_alt_short_press
    subtype: button_2
  action:
  - service: input_select.select_option
    entity_id: input_select.bedroom_mode
    data:
      option: 'Empty'

#
# Lights / radio based on mode
#

- alias: 'Bedroom: Any to Empty'
  trigger:
    platform: state
    entity_id: input_select.bedroom_mode
    to: 'Empty'
  action:
    service: script.bedroom_lights_off

- alias: 'Bedroom: Any to Work'
  trigger:
    platform: state
    entity_id: input_select.bedroom_mode
    to: 'Work'
  action:
    service: script.bedroom_lights_full

- alias: 'Bedroom: Any to Wakedown'
  trigger:
    platform: state
    entity_id: input_select.bedroom_mode
    to: 'Wakedown'
  action:
    service: script.bedroom_lights_half

- alias: 'Bedroom: Any to Wakeup'
  trigger:
    platform: state
    entity_id: input_select.bedroom_mode
    to: 'Wakeup'
  action:
  - service: script.bedroom_lights_half
  - service: script.bedroom_radio_on

- alias: 'Bedroom: Wakeup to Any'
  trigger:
    platform: state
    entity_id: input_select.bedroom_mode
    from: 'Wakeup'
  action:
  - service: script.bedroom_radio_off
  - service: timer.cancel
    entity_id: timer.wakeup_alarm_timeout


#
# Alarm
#

- alias: Wakeup Alarm
  trigger:
  - platform: time
    at: input_datetime.wakeup_time
  condition:
  - condition: state
    entity_id: input_boolean.wakeup_alarm
    state: 'on'
  action:
  - service: input_select.select_option
    entity_id: input_select.bedroom_mode
    data:
      option: "Wakeup"
  - service: timer.start
    entity_id: timer.wakeup_alarm_timeout
    data:
      duration: '01:00:00'



- alias: Wakeup Alarm auto-off
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.wakeup_alarm_timeout
  condition: []
  action:
  - service: input_select.select_option
    entity_id: input_select.bedroom_mode
    data:
      option: 'Empty'  

