
#
# Double 4 -> Turn off all things
#

- alias: Any Button 4
  trigger:
  - platform: device
    device_id: cb927dc8f9bc81d7fad027c512a60c80
    domain: zha
    type: remote_button_alt_double_press
    subtype: button_4
  - platform: device
    device_id: f54b5fae010cb7fa45492f457fe71b43
    domain: zha
    type: remote_button_alt_double_press
    subtype: button_4
  action:
  - service: script.global_all_off

