


- alias: Entry Door Opened Notification
  trigger:
  - platform: state
    entity_id: binary_sensor.entry_door
    to: 'on'
  action:
  - service: notify.notify_telegram
    data:
      message: Eingangstür geöffnet



- alias: Entry Camera Motion Notification
  trigger:
  - platform: state
    entity_id: binary_sensor.tapo_camera_eingang_motion
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.at_home
      state: 'off'
  action:
  - service: camera.snapshot
    entity_id: camera.tapo_camera_eingang_sd
    data:
      filename: '/config/www/data/eingang_1.jpg'
  - delay: '00:00:01'
  - service: camera.snapshot
    entity_id: camera.tapo_camera_eingang_sd
    data:
      filename: '/config/www/data/eingang_2.jpg'
  - delay: '00:00:01'
  - service: camera.snapshot
    entity_id: camera.tapo_camera_eingang_sd
    data:
      filename: '/config/www/data/eingang_3.jpg'
  - service: notify.notify_telegram
    data:
      message: foo
      data:
        photo:
        - file: '/config/www/data/eingang_1.jpg'
          caption: Bewegung im Eingangsbereich 1
        - file: '/config/www/data/eingang_2.jpg'
          caption: Bewegung im Eingangsbereich 2
        - file: '/config/www/data/eingang_3.jpg'
          caption: Bewegung im Eingangsbereich 3



- alias: Bath Waterleak Notification
  trigger:
  - platform: state
    entity_id: binary_sensor.bath_waterleak
    to: 'on'
  action:
  - service: notify.notify_telegram
    data:
      message: Wasserleck Bad !!



- alias: Kitchen Waterleak Notification
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_waterleak
    to: 'on'
  action:
  - service: notify.notify_telegram
    data:
      message: Wasserleck Küche !!



- alias: Home Zone Left
  trigger:
  - platform: state
    entity_id: device_tracker.pocof2pro_pocof2pro
    to: not_home
  action:
  - service: notify.notify_telegram
    data:
      message: 'Zone verlassen. AtHome=False'
  - service: input_boolean.turn_off
    entity_id: input_boolean.at_home



- alias: Home Zone Entered
  trigger:
  - platform: state
    entity_id: device_tracker.pocof2pro_pocof2pro
    to: home
  action:
  - service: notify.notify_telegram
    data:
      message: 'Zone betreten. AtHome=True'
  - service: input_boolean.turn_on
    entity_id: input_boolean.at_home
